// Generated by jextract

package org.unix;

/**
 * {@snippet :
 * typedef struct _opaque_pthread_rwlockattr_t __darwin_pthread_rwlockattr_t;
 * }
 */
public final class __darwin_pthread_rwlockattr_t extends _opaque_pthread_rwlockattr_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private __darwin_pthread_rwlockattr_t() {}
}


