// Generated by jextract

package org.unix;

/**
 * {@snippet :
 * import org.unix._opaque_pthread_mutexattr_t;typedef struct _opaque_pthread_mutexattr_t __darwin_pthread_mutexattr_t;
 *}
 */
public final class __darwin_pthread_mutexattr_t extends _opaque_pthread_mutexattr_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private __darwin_pthread_mutexattr_t() {}
}


