// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;

final class constants$54 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$54() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "setkey",
        constants$0.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "setlogin",
        constants$24.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "setmode",
        constants$10.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "setrgid",
        constants$16.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "setruid",
        constants$16.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "setsgroups_np",
        constants$28.const$3
    );
}


