// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "timingsafe_bcmp",
        constants$5.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "strsignal_r",
        constants$10.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "bcmp",
        constants$5.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "bcopy",
        constants$13.const$0
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "bzero",
        constants$15.const$4
    );
}


