// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

final class constants$21 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$21() {}
    static final FunctionDescriptor mktemp$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mktemp$MH = RuntimeHelper.downcallHandle(
        "mktemp",
        constants$21.mktemp$FUNC
    );
    static final FunctionDescriptor mkostemp$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mkostemp$MH = RuntimeHelper.downcallHandle(
        "mkostemp",
        constants$21.mkostemp$FUNC
    );
    static final FunctionDescriptor mkostemps$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mkostemps$MH = RuntimeHelper.downcallHandle(
        "mkostemps",
        constants$21.mkostemps$FUNC
    );
    static final FunctionDescriptor mkstemp_dprotected_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mkstemp_dprotected_np$MH = RuntimeHelper.downcallHandle(
        "mkstemp_dprotected_np",
        constants$21.mkstemp_dprotected_np$FUNC
    );
    static final FunctionDescriptor mkdtempat_np$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mkdtempat_np$MH = RuntimeHelper.downcallHandle(
        "mkdtempat_np",
        constants$21.mkdtempat_np$FUNC
    );
    static final FunctionDescriptor mkstempsat_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mkstempsat_np$MH = RuntimeHelper.downcallHandle(
        "mkstempsat_np",
        constants$21.mkstempsat_np$FUNC
    );
}


