// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.StructLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.*;
final class constants$43 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$43() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_LONG.withName("tv_sec"),
        JAVA_INT.withName("tv_usec"),
        MemoryLayout.paddingLayout(32)
    ).withName("timeval");
    static final VarHandle const$1 = constants$43.const$0.varHandle(PathElement.groupElement("tv_sec"));
    static final VarHandle const$2 = constants$43.const$0.varHandle(PathElement.groupElement("tv_usec"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "pselect",
        constants$43.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "select",
        constants$43.const$5
    );
}


