// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final FunctionDescriptor mkostempsat_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mkostempsat_np$MH = RuntimeHelper.downcallHandle(
        "mkostempsat_np",
        constants$22.mkostempsat_np$FUNC
    );
    static final FunctionDescriptor nfssvc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nfssvc$MH = RuntimeHelper.downcallHandle(
        "nfssvc",
        constants$22.nfssvc$FUNC
    );
    static final FunctionDescriptor profil$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle profil$MH = RuntimeHelper.downcallHandle(
        "profil",
        constants$22.profil$FUNC
    );
    static final FunctionDescriptor pthread_setugid_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pthread_setugid_np$MH = RuntimeHelper.downcallHandle(
        "pthread_setugid_np",
        constants$22.pthread_setugid_np$FUNC
    );
    static final FunctionDescriptor pthread_getugid_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_getugid_np$MH = RuntimeHelper.downcallHandle(
        "pthread_getugid_np",
        constants$22.pthread_getugid_np$FUNC
    );
    static final FunctionDescriptor reboot$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle reboot$MH = RuntimeHelper.downcallHandle(
        "reboot",
        constants$22.reboot$FUNC
    );
}


