// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

final class constants$18 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$18() {}
    static final FunctionDescriptor execvP$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle execvP$MH = RuntimeHelper.downcallHandle(
        "execvP",
        constants$18.execvP$FUNC
    );
    static final FunctionDescriptor fflagstostr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle fflagstostr$MH = RuntimeHelper.downcallHandle(
        "fflagstostr",
        constants$18.fflagstostr$FUNC
    );
    static final FunctionDescriptor getdomainname$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle getdomainname$MH = RuntimeHelper.downcallHandle(
        "getdomainname",
        constants$18.getdomainname$FUNC
    );
    static final FunctionDescriptor getgrouplist$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle getgrouplist$MH = RuntimeHelper.downcallHandle(
        "getgrouplist",
        constants$18.getgrouplist$FUNC
    );
    static final FunctionDescriptor gethostuuid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gethostuuid$MH = RuntimeHelper.downcallHandle(
        "gethostuuid",
        constants$18.gethostuuid$FUNC
    );
    static final FunctionDescriptor getmode$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle getmode$MH = RuntimeHelper.downcallHandle(
        "getmode",
        constants$18.getmode$FUNC
    );
}


