// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;

final class constants$50 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$50() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "mkstempsat_np",
        constants$23.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "mkostempsat_np",
        constants$22.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "nfssvc",
        constants$28.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "profil",
        constants$44.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "pthread_setugid_np",
        constants$25.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "pthread_getugid_np",
        constants$6.const$4
    );
}


