// Generated by jextract

package org.unix;

import java.lang.foreign.MemorySegment;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
final class constants$34 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$34() {}
    static final VarHandle const$0 = RuntimeHelper.POINTER.varHandle();
    static final MemorySegment const$1 = RuntimeHelper.lookupGlobalVariable("optarg", RuntimeHelper.POINTER);
    static final VarHandle const$2 = JAVA_INT.varHandle();
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("optind", JAVA_INT);
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("opterr", JAVA_INT);
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("optopt", JAVA_INT);
}


