// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {}
    static final FunctionDescriptor setkey$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle setkey$MH = RuntimeHelper.downcallHandle(
        "setkey",
        constants$25.setkey$FUNC
    );
    static final FunctionDescriptor setlogin$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle setlogin$MH = RuntimeHelper.downcallHandle(
        "setlogin",
        constants$25.setlogin$FUNC
    );
    static final FunctionDescriptor setmode$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle setmode$MH = RuntimeHelper.downcallHandle(
        "setmode",
        constants$25.setmode$FUNC
    );
    static final FunctionDescriptor setrgid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle setrgid$MH = RuntimeHelper.downcallHandle(
        "setrgid",
        constants$25.setrgid$FUNC
    );
    static final FunctionDescriptor setruid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle setruid$MH = RuntimeHelper.downcallHandle(
        "setruid",
        constants$25.setruid$FUNC
    );
    static final FunctionDescriptor setsgroups_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle setsgroups_np$MH = RuntimeHelper.downcallHandle(
        "setsgroups_np",
        constants$25.setsgroups_np$FUNC
    );
}


