// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
final class constants$35 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$35() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ctermid",
        constants$10.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "brk",
        constants$10.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "chroot",
        constants$24.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "crypt",
        constants$6.const$0
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "encrypt",
        constants$35.const$4
    );
}


