// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$36 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$36() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fchdir",
        constants$16.const$2
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_LONG);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "gethostid",
        constants$36.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getpgid",
        constants$16.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getsid",
        constants$16.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getdtablesize",
        constants$27.const$1
    );
}


