// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}
    static final FunctionDescriptor revoke$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle revoke$MH = RuntimeHelper.downcallHandle(
        "revoke",
        constants$23.revoke$FUNC
    );
    static final FunctionDescriptor rcmd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcmd$MH = RuntimeHelper.downcallHandle(
        "rcmd",
        constants$23.rcmd$FUNC
    );
    static final FunctionDescriptor rcmd_af$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle rcmd_af$MH = RuntimeHelper.downcallHandle(
        "rcmd_af",
        constants$23.rcmd_af$FUNC
    );
    static final FunctionDescriptor rresvport$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rresvport$MH = RuntimeHelper.downcallHandle(
        "rresvport",
        constants$23.rresvport$FUNC
    );
    static final FunctionDescriptor rresvport_af$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle rresvport_af$MH = RuntimeHelper.downcallHandle(
        "rresvport_af",
        constants$23.rresvport_af$FUNC
    );
    static final FunctionDescriptor iruserok$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle iruserok$MH = RuntimeHelper.downcallHandle(
        "iruserok",
        constants$23.iruserok$FUNC
    );
}


