// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$56 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$56() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "unwhiteout",
        constants$24.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "valloc",
        constants$45.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandleVariadic(
        "syscall",
        constants$16.const$2
    );
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("suboptarg", RuntimeHelper.POINTER);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getsubopt",
        constants$26.const$4
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "fgetattrlist",
        constants$56.const$5
    );
}


