// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
final class constants$26 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$26() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandleVariadic(
        "execl",
        constants$6.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandleVariadic(
        "execle",
        constants$6.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandleVariadic(
        "execlp",
        constants$6.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "execv",
        constants$6.const$4
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "execve",
        constants$26.const$4
    );
}


