// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.OfAddress;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final FunctionDescriptor unwhiteout$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle unwhiteout$MH = RuntimeHelper.downcallHandle(
        "unwhiteout",
        constants$27.unwhiteout$FUNC
    );
    static final FunctionDescriptor valloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle valloc$MH = RuntimeHelper.downcallHandle(
        "valloc",
        constants$27.valloc$FUNC
    );
    static final FunctionDescriptor syscall$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle syscall$MH = RuntimeHelper.downcallHandleVariadic(
        "syscall",
        constants$27.syscall$FUNC
    );
    static final OfAddress suboptarg$LAYOUT = Constants$root.C_POINTER$LAYOUT;
    static final VarHandle suboptarg$VH = constants$27.suboptarg$LAYOUT.varHandle();
    static final MemorySegment suboptarg$SEGMENT = RuntimeHelper.lookupGlobalVariable("suboptarg", constants$27.suboptarg$LAYOUT);
    static final FunctionDescriptor getsubopt$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle getsubopt$MH = RuntimeHelper.downcallHandle(
        "getsubopt",
        constants$27.getsubopt$FUNC
    );
    static final FunctionDescriptor fgetattrlist$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle fgetattrlist$MH = RuntimeHelper.downcallHandle(
        "fgetattrlist",
        constants$27.fgetattrlist$FUNC
    );
}


