// Generated by jextract

package org.unix;

import java.lang.foreign.MemoryLayout;
import java.lang.foreign.StructLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.*;
final class constants$42 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$42() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "symlink",
        constants$6.const$4
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(32, JAVA_INT).withName("fds_bits")
    ).withName("fd_set");
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "__darwin_check_fd_set_overflow",
        constants$23.const$4
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_LONG.withName("tv_sec"),
        JAVA_LONG.withName("tv_nsec")
    ).withName("timespec");
    static final VarHandle const$4 = constants$42.const$3.varHandle(PathElement.groupElement("tv_sec"));
    static final VarHandle const$5 = constants$42.const$3.varHandle(PathElement.groupElement("tv_nsec"));
}


