// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;

final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "setusershell",
        constants$39.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "setwgroups_np",
        constants$28.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "strtofflags",
        constants$26.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "swapon",
        constants$24.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ttyslot",
        constants$27.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "undelete",
        constants$24.const$5
    );
}


