// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;

final class constants$29 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$29() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getpgrp",
        constants$27.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getpid",
        constants$27.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getppid",
        constants$27.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getuid",
        constants$27.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "isatty",
        constants$16.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "link",
        constants$6.const$4
    );
}


