// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
final class constants$28 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$28() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getegid",
        constants$27.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "geteuid",
        constants$27.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getgid",
        constants$27.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getgroups",
        constants$28.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getlogin",
        constants$18.const$0
    );
}


