// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
final class constants$41 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$41() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "fchown",
        constants$41.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "gethostname",
        constants$39.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "readlink",
        constants$9.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "setegid",
        constants$16.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "seteuid",
        constants$16.const$2
    );
}


