// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "index",
        constants$6.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rindex",
        constants$6.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ffs",
        constants$16.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "strcasecmp",
        constants$6.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "strncasecmp",
        constants$5.const$0
    );
}


