// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
final class constants$14 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$14() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "strlcat",
        constants$9.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "strlcpy",
        constants$9.const$4
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "strmode",
        constants$14.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "strsep",
        constants$6.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "swab",
        constants$13.const$0
    );
}


