// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.StructLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.*;
final class constants$20 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$20() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandleVariadic(
        "ioctl",
        constants$20.const$0
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("ad_name_offset"),
        JAVA_INT.withName("ad_flags"),
        MemoryLayout.sequenceLayout(2, JAVA_INT).withName("ad_pad")
    ).withName("accessx_descriptor");
    static final VarHandle const$3 = constants$20.const$2.varHandle(PathElement.groupElement("ad_name_offset"));
    static final VarHandle const$4 = constants$20.const$2.varHandle(PathElement.groupElement("ad_flags"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "getattrlistbulk",
        constants$20.const$5
    );
}


