// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;

final class constants$40 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$40() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ualarm",
        constants$25.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "usleep",
        constants$16.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "vfork",
        constants$27.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "fsync",
        constants$16.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ftruncate",
        constants$20.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getlogin_r",
        constants$39.const$4
    );
}


