// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_SHORT;
final class constants$48 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$48() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_SHORT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "mkpath_np",
        constants$48.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_SHORT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mkpathat_np",
        constants$48.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "mkstemp",
        constants$24.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mkstemps",
        constants$24.const$2
    );
}


