// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$39 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$39() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "setregid",
        constants$25.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "setreuid",
        constants$25.const$4
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid();
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "sync",
        constants$39.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "truncate",
        constants$39.const$4
    );
}


