// Generated by jextract

package org.unix;

import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
final class constants$59 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$59() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fsync_volume_np",
        constants$25.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "sync_volume_np",
        constants$24.const$2
    );
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("optreset", JAVA_INT);
    static final MemorySegment const$3 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("$DARWIN_EXTSN");
    static final MemorySegment const$4 = MemorySegment.ofAddress(0L);
}


