// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$45 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$45() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "endusershell",
        constants$39.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "execvP",
        constants$26.const$4
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "fflagstostr",
        constants$45.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getdomainname",
        constants$24.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "getgrouplist",
        constants$45.const$5
    );
}


