// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$37 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$37() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getpagesize",
        constants$27.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "getpass",
        constants$10.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getwd",
        constants$10.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "lchown",
        constants$25.const$0
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "lockf",
        constants$37.const$4
    );
}


