// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ffsl",
        constants$17.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ffsll",
        constants$17.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "fls",
        constants$16.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "flsl",
        constants$17.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "flsll",
        constants$17.const$0
    );
}


