// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$52 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$52() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "rresvport",
        constants$24.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rresvport_af",
        constants$24.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "iruserok",
        constants$52.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "iruserok_sa",
        constants$52.const$4
    );
}


