// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;

final class constants$31 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$31() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "read",
        constants$21.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "rmdir",
        constants$24.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "setgid",
        constants$16.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "setpgid",
        constants$25.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "setsid",
        constants$27.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "setuid",
        constants$16.const$2
    );
}


