// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$32 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$32() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "sleep",
        constants$16.const$2
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sysconf",
        constants$32.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "tcgetpgrp",
        constants$16.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "tcsetpgrp",
        constants$25.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ttyname",
        constants$7.const$4
    );
}


