// Generated by jextract

package org.unix;

import java.lang.foreign.MemoryLayout;
import java.lang.foreign.StructLayout;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.JAVA_SHORT;
import static java.lang.foreign.ValueLayout.PathElement;
final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {}
    static final VarHandle const$0 = constants$18.const$2.varHandle(PathElement.groupElement("ws_ypixel"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_SHORT.withName("ts_lines"),
        JAVA_SHORT.withName("ts_cols"),
        JAVA_SHORT.withName("ts_xxx"),
        JAVA_SHORT.withName("ts_yyy")
    ).withName("ttysize");
    static final VarHandle const$2 = constants$19.const$1.varHandle(PathElement.groupElement("ts_lines"));
    static final VarHandle const$3 = constants$19.const$1.varHandle(PathElement.groupElement("ts_cols"));
    static final VarHandle const$4 = constants$19.const$1.varHandle(PathElement.groupElement("ts_xxx"));
    static final VarHandle const$5 = constants$19.const$1.varHandle(PathElement.groupElement("ts_yyy"));
}


