// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_SHORT;
final class constants$47 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$47() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "getwgroups_np",
        constants$6.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "initgroups",
        constants$24.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "issetugid",
        constants$27.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "mkdtemp",
        constants$10.const$4
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_SHORT,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "mknod",
        constants$47.const$4
    );
}


