// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_SHORT;
final class constants$46 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$46() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "gethostuuid",
        constants$6.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_SHORT,
        RuntimeHelper.POINTER,
        JAVA_SHORT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "getmode",
        constants$46.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "getpeereid",
        constants$33.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "getsgroups_np",
        constants$6.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getusershell",
        constants$18.const$0
    );
}


