// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$53 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$53() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ruserok",
        constants$45.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "setdomainname",
        constants$24.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "setgroups",
        constants$28.const$3
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        JAVA_LONG
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "sethostid",
        constants$53.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "sethostname",
        constants$24.const$2
    );
}


