// Generated by jextract

package org.unix;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "execvp",
        constants$6.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "fork",
        constants$27.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "fpathconf",
        constants$27.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "getcwd",
        constants$11.const$4
    );
}


