// Generated by jextract

package org.unix;

import java.lang.foreign.*;

/**
 * {@snippet :
 * struct fd_set {
 *     __int32_t fds_bits[32];
 * };
 * }
 */
public class fd_set {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(32, Constants$root.C_INT$LAYOUT).withName("fds_bits")
    ).withName("fd_set");
    public static MemoryLayout $LAYOUT() {
        return fd_set.$struct$LAYOUT;
    }
    public static MemorySegment fds_bits$slice(MemorySegment seg) {
        return seg.asSlice(0, 128);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


