// Generated by jextract

package org.unix;

public class Linux_1 {

    /**
     * {@snippet :
     * #define W_OK 2
     * }
     */
    public static int W_OK() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define R_OK 4
     * }
     */
    public static int R_OK() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define _READ_OK 512
     * }
     */
    public static int _READ_OK() {
        return (int)512L;
    }
    /**
     * {@snippet :
     * #define _WRITE_OK 1024
     * }
     */
    public static int _WRITE_OK() {
        return (int)1024L;
    }
    /**
     * {@snippet :
     * #define _EXECUTE_OK 2048
     * }
     */
    public static int _EXECUTE_OK() {
        return (int)2048L;
    }
    /**
     * {@snippet :
     * #define _DELETE_OK 4096
     * }
     */
    public static int _DELETE_OK() {
        return (int)4096L;
    }
    /**
     * {@snippet :
     * #define _APPEND_OK 8192
     * }
     */
    public static int _APPEND_OK() {
        return (int)8192L;
    }
    /**
     * {@snippet :
     * #define _RMFILE_OK 16384
     * }
     */
    public static int _RMFILE_OK() {
        return (int)16384L;
    }
    /**
     * {@snippet :
     * #define _RATTR_OK 32768
     * }
     */
    public static int _RATTR_OK() {
        return (int)32768L;
    }
    /**
     * {@snippet :
     * #define _WATTR_OK 65536
     * }
     */
    public static int _WATTR_OK() {
        return (int)65536L;
    }
    /**
     * {@snippet :
     * #define _REXT_OK 131072
     * }
     */
    public static int _REXT_OK() {
        return (int)131072L;
    }
    /**
     * {@snippet :
     * #define _WEXT_OK 262144
     * }
     */
    public static int _WEXT_OK() {
        return (int)262144L;
    }
    /**
     * {@snippet :
     * #define _RPERM_OK 524288
     * }
     */
    public static int _RPERM_OK() {
        return (int)524288L;
    }
    /**
     * {@snippet :
     * #define _WPERM_OK 1048576
     * }
     */
    public static int _WPERM_OK() {
        return (int)1048576L;
    }
    /**
     * {@snippet :
     * #define _CHOWN_OK 2097152
     * }
     */
    public static int _CHOWN_OK() {
        return (int)2097152L;
    }
    /**
     * {@snippet :
     * #define _ACCESS_EXTENDED_MASK 4193792
     * }
     */
    public static int _ACCESS_EXTENDED_MASK() {
        return (int)4193792L;
    }
    /**
     * {@snippet :
     * #define L_SET 0
     * }
     */
    public static int L_SET() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define L_INCR 1
     * }
     */
    public static int L_INCR() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define L_XTND 2
     * }
     */
    public static int L_XTND() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define ACCESSX_MAX_TABLESIZE 16384
     * }
     */
    public static int ACCESSX_MAX_TABLESIZE() {
        return (int)16384L;
    }
    /**
     * {@snippet :
     * #define _POSIX_ADVISORY_INFO -1
     * }
     */
    public static int _POSIX_ADVISORY_INFO() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_ASYNCHRONOUS_IO -1
     * }
     */
    public static int _POSIX_ASYNCHRONOUS_IO() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_BARRIERS -1
     * }
     */
    public static int _POSIX_BARRIERS() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_CHOWN_RESTRICTED 200112
     * }
     */
    public static long _POSIX_CHOWN_RESTRICTED() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_CLOCK_SELECTION -1
     * }
     */
    public static int _POSIX_CLOCK_SELECTION() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_CPUTIME -1
     * }
     */
    public static int _POSIX_CPUTIME() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_FSYNC 200112
     * }
     */
    public static long _POSIX_FSYNC() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_IPV6 200112
     * }
     */
    public static long _POSIX_IPV6() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_JOB_CONTROL 200112
     * }
     */
    public static long _POSIX_JOB_CONTROL() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_MAPPED_FILES 200112
     * }
     */
    public static long _POSIX_MAPPED_FILES() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_MEMLOCK -1
     * }
     */
    public static int _POSIX_MEMLOCK() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_MEMLOCK_RANGE -1
     * }
     */
    public static int _POSIX_MEMLOCK_RANGE() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_MEMORY_PROTECTION 200112
     * }
     */
    public static long _POSIX_MEMORY_PROTECTION() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_MESSAGE_PASSING -1
     * }
     */
    public static int _POSIX_MESSAGE_PASSING() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_MONOTONIC_CLOCK -1
     * }
     */
    public static int _POSIX_MONOTONIC_CLOCK() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_NO_TRUNC 200112
     * }
     */
    public static long _POSIX_NO_TRUNC() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_PRIORITIZED_IO -1
     * }
     */
    public static int _POSIX_PRIORITIZED_IO() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_PRIORITY_SCHEDULING -1
     * }
     */
    public static int _POSIX_PRIORITY_SCHEDULING() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_RAW_SOCKETS -1
     * }
     */
    public static int _POSIX_RAW_SOCKETS() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_READER_WRITER_LOCKS 200112
     * }
     */
    public static long _POSIX_READER_WRITER_LOCKS() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_REALTIME_SIGNALS -1
     * }
     */
    public static int _POSIX_REALTIME_SIGNALS() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_REGEXP 200112
     * }
     */
    public static long _POSIX_REGEXP() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_SAVED_IDS 200112
     * }
     */
    public static long _POSIX_SAVED_IDS() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_SEMAPHORES -1
     * }
     */
    public static int _POSIX_SEMAPHORES() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_SHARED_MEMORY_OBJECTS -1
     * }
     */
    public static int _POSIX_SHARED_MEMORY_OBJECTS() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_SHELL 200112
     * }
     */
    public static long _POSIX_SHELL() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_SPAWN 200112
     * }
     */
    public static long _POSIX_SPAWN() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_SPIN_LOCKS -1
     * }
     */
    public static int _POSIX_SPIN_LOCKS() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_SPORADIC_SERVER -1
     * }
     */
    public static int _POSIX_SPORADIC_SERVER() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_SYNCHRONIZED_IO -1
     * }
     */
    public static int _POSIX_SYNCHRONIZED_IO() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_THREAD_ATTR_STACKADDR 200112
     * }
     */
    public static long _POSIX_THREAD_ATTR_STACKADDR() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_THREAD_ATTR_STACKSIZE 200112
     * }
     */
    public static long _POSIX_THREAD_ATTR_STACKSIZE() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_THREAD_CPUTIME -1
     * }
     */
    public static int _POSIX_THREAD_CPUTIME() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_THREAD_PRIO_INHERIT -1
     * }
     */
    public static int _POSIX_THREAD_PRIO_INHERIT() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_THREAD_PRIO_PROTECT -1
     * }
     */
    public static int _POSIX_THREAD_PRIO_PROTECT() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_THREAD_PRIORITY_SCHEDULING -1
     * }
     */
    public static int _POSIX_THREAD_PRIORITY_SCHEDULING() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_THREAD_PROCESS_SHARED 200112
     * }
     */
    public static long _POSIX_THREAD_PROCESS_SHARED() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_THREAD_SAFE_FUNCTIONS 200112
     * }
     */
    public static long _POSIX_THREAD_SAFE_FUNCTIONS() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_THREAD_SPORADIC_SERVER -1
     * }
     */
    public static int _POSIX_THREAD_SPORADIC_SERVER() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_THREADS 200112
     * }
     */
    public static long _POSIX_THREADS() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX_TIMEOUTS -1
     * }
     */
    public static int _POSIX_TIMEOUTS() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_TIMERS -1
     * }
     */
    public static int _POSIX_TIMERS() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_TRACE -1
     * }
     */
    public static int _POSIX_TRACE() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_TRACE_EVENT_FILTER -1
     * }
     */
    public static int _POSIX_TRACE_EVENT_FILTER() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_TRACE_INHERIT -1
     * }
     */
    public static int _POSIX_TRACE_INHERIT() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_TRACE_LOG -1
     * }
     */
    public static int _POSIX_TRACE_LOG() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_TYPED_MEMORY_OBJECTS -1
     * }
     */
    public static int _POSIX_TYPED_MEMORY_OBJECTS() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX2_C_BIND 200112
     * }
     */
    public static long _POSIX2_C_BIND() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX2_C_DEV 200112
     * }
     */
    public static long _POSIX2_C_DEV() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX2_CHAR_TERM 200112
     * }
     */
    public static long _POSIX2_CHAR_TERM() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX2_FORT_DEV -1
     * }
     */
    public static int _POSIX2_FORT_DEV() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX2_FORT_RUN 200112
     * }
     */
    public static long _POSIX2_FORT_RUN() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX2_LOCALEDEF 200112
     * }
     */
    public static long _POSIX2_LOCALEDEF() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX2_PBS -1
     * }
     */
    public static int _POSIX2_PBS() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX2_PBS_ACCOUNTING -1
     * }
     */
    public static int _POSIX2_PBS_ACCOUNTING() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX2_PBS_CHECKPOINT -1
     * }
     */
    public static int _POSIX2_PBS_CHECKPOINT() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX2_PBS_LOCATE -1
     * }
     */
    public static int _POSIX2_PBS_LOCATE() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX2_PBS_MESSAGE -1
     * }
     */
    public static int _POSIX2_PBS_MESSAGE() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX2_PBS_TRACK -1
     * }
     */
    public static int _POSIX2_PBS_TRACK() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX2_SW_DEV 200112
     * }
     */
    public static long _POSIX2_SW_DEV() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define _POSIX2_UPE 200112
     * }
     */
    public static long _POSIX2_UPE() {
        return 200112L;
    }
    /**
     * {@snippet :
     * #define __ILP32_OFF32 -1
     * }
     */
    public static int __ILP32_OFF32() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define __ILP32_OFFBIG -1
     * }
     */
    public static int __ILP32_OFFBIG() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define __LP64_OFF64 1
     * }
     */
    public static int __LP64_OFF64() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __LPBIG_OFFBIG 1
     * }
     */
    public static int __LPBIG_OFFBIG() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_V6_ILP32_OFF32 -1
     * }
     */
    public static int _POSIX_V6_ILP32_OFF32() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_V6_ILP32_OFFBIG -1
     * }
     */
    public static int _POSIX_V6_ILP32_OFFBIG() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_V6_LP64_OFF64 1
     * }
     */
    public static int _POSIX_V6_LP64_OFF64() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_V6_LPBIG_OFFBIG 1
     * }
     */
    public static int _POSIX_V6_LPBIG_OFFBIG() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_V7_ILP32_OFF32 -1
     * }
     */
    public static int _POSIX_V7_ILP32_OFF32() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_V7_ILP32_OFFBIG -1
     * }
     */
    public static int _POSIX_V7_ILP32_OFFBIG() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_V7_LP64_OFF64 1
     * }
     */
    public static int _POSIX_V7_LP64_OFF64() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_V7_LPBIG_OFFBIG 1
     * }
     */
    public static int _POSIX_V7_LPBIG_OFFBIG() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _V6_ILP32_OFF32 -1
     * }
     */
    public static int _V6_ILP32_OFF32() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _V6_ILP32_OFFBIG -1
     * }
     */
    public static int _V6_ILP32_OFFBIG() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _V6_LP64_OFF64 1
     * }
     */
    public static int _V6_LP64_OFF64() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _V6_LPBIG_OFFBIG 1
     * }
     */
    public static int _V6_LPBIG_OFFBIG() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _XBS5_ILP32_OFF32 -1
     * }
     */
    public static int _XBS5_ILP32_OFF32() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _XBS5_ILP32_OFFBIG -1
     * }
     */
    public static int _XBS5_ILP32_OFFBIG() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _XBS5_LP64_OFF64 1
     * }
     */
    public static int _XBS5_LP64_OFF64() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _XBS5_LPBIG_OFFBIG 1
     * }
     */
    public static int _XBS5_LPBIG_OFFBIG() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _XOPEN_CRYPT 1
     * }
     */
    public static int _XOPEN_CRYPT() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _XOPEN_ENH_I18N 1
     * }
     */
    public static int _XOPEN_ENH_I18N() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _XOPEN_LEGACY -1
     * }
     */
    public static int _XOPEN_LEGACY() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _XOPEN_REALTIME -1
     * }
     */
    public static int _XOPEN_REALTIME() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _XOPEN_REALTIME_THREADS -1
     * }
     */
    public static int _XOPEN_REALTIME_THREADS() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _XOPEN_SHM 1
     * }
     */
    public static int _XOPEN_SHM() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _XOPEN_STREAMS -1
     * }
     */
    public static int _XOPEN_STREAMS() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define _XOPEN_UNIX 1
     * }
     */
    public static int _XOPEN_UNIX() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _SC_PAGE_SIZE 29
     * }
     */
    public static int _SC_PAGE_SIZE() {
        return (int)29L;
    }
    /**
     * {@snippet :
     * #define __DARWIN_NFDBITS 32
     * }
     */
    public static long __DARWIN_NFDBITS() {
        return 32L;
    }
    /**
     * {@snippet :
     * #define FD_SETSIZE 1024
     * }
     */
    public static int FD_SETSIZE() {
        return (int)1024L;
    }
}


