// Generated by jextract

package org.unix;

import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.*;
public class Linux  {

    public static final OfByte C_CHAR = Constants$root.C_CHAR$LAYOUT;
    public static final OfShort C_SHORT = Constants$root.C_SHORT$LAYOUT;
    public static final OfInt C_INT = Constants$root.C_INT$LAYOUT;
    public static final OfLong C_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static final OfLong C_LONG_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static final OfFloat C_FLOAT = Constants$root.C_FLOAT$LAYOUT;
    public static final OfDouble C_DOUBLE = Constants$root.C_DOUBLE$LAYOUT;
    public static final OfAddress C_POINTER = Constants$root.C_POINTER$LAYOUT;
    /**
     * {@snippet :
     * #define STDIN_FILENO 0
     * }
     */
    public static int STDIN_FILENO() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define STDOUT_FILENO 1
     * }
     */
    public static int STDOUT_FILENO() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define STDERR_FILENO 2
     * }
     */
    public static int STDERR_FILENO() {
        return (int)2L;
    }
    public static MethodHandle ioctl$MH() {
        return RuntimeHelper.requireNonNull(constants$0.ioctl$MH,"ioctl");
    }
    /**
     * {@snippet :
     * int ioctl(int, unsigned long,...);
     * }
     */
    public static int ioctl(int x0, long x1, Object... x2) {
        var mh$ = ioctl$MH();
        try {
            return (int)mh$.invokeExact(x0, x1, x2);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    /**
     * {@snippet :
     * #define TIOCGWINSZ 1074295912
     * }
     */
    public static long TIOCGWINSZ() {
        return 1074295912L;
    }
}


