name: Kotlin Script

on:
  push:
    branches:
      - main
    tags:
      - '*'

  pull_request:
    branches:
      - main

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  kotlin-script:
    name: Run Kotlin Script
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest, macos-14 ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: 🚀 Run Kotlin Script on ${{ matrix.os }}
        id: kotlin-script-exec
        uses: sureshg/kts-exec@v2.6
        with:
          script: "script.main.kts"
          compiler-plugin: kotlinx-serialization

      - name: Print Kotlin install and compiler plugin path
        run: |
          java -version
          echo "Plugin Path : ${{ steps.kotlin-script-exec.outputs.plugin-path }}"
          echo "Kotlin Root : ${{ steps.kotlin-script-exec.outputs.kotlin-root }}"
