name: Kotlin Script

on:
  push:
    branches:
      - main
    tags:
      - '*'

  pull_request:
    branches:
      - main

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

defaults:
  run:
    shell: bash


jobs:
  kotlin-script:
    name: Run Kotlin Script
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: 🚀 Run Kotlin Script on ${{ matrix.os }}
        id: kotlin-script-exec
        uses: sureshg/kts-exec@v2.2
        with:
          script: "script.main.kts"
          compiler-plugin: kotlinx-serialization

      - name: Print compiler plugin path
        run: |
          java -version
          echo ${{ steps.kotlin-script-exec.outputs.plugin-path }}
