name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Drafts next Release notes
        uses: release-drafter/release-drafter@v6
        with:
          config-name: config/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}